INSERT INTO `products` (`name`,`price`,`description`) VALUES 
("Abyssinian", "1120", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Aegean", "1000", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("American Curl", "1300", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("American Bobtail", "1600", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("American Shorthair", "1800", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("British Semi-longhair", "1900", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("British Shorthair", "2200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Burmese", "3200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Burmilla", "4200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Chantilly-Tiffany", "5200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Chartreux", "6200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Chausie", "400", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Cheetoh", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dragon Li", "120", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Devon Rex", "10", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Egyptian Mau", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("European Shorthair", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Exotic Shorthair", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Foldex", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("German Rex", "20", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Havana Brown", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Highlander", "200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Himalayan", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Japanese Bobtail", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Javanese", "1220", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Khao Manee", "120", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Korean Bobtail", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Savannah", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Pixie-bob", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Peterbald", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Munchkin", "12100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Nebelung", "2", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Ocicat", "12", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Toyger", "12", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Tonkinese", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Siamese", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Thai Lilac", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Suphalak", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Sphynx", "1200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Singapura", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("York Chocolate", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Ukrainian Levkoy", "200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Turkish Van", "200", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Turkish Angora", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Dummy Data", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus."),
("Korat", "100", "Lorem ipsum dolor sit amet, illum percipitur eu vis. Ut quis melius vis. Corpora periculis id mea. Elitr molestiae vix id, nam at nemore blandit sensibus.");

SELECT '---Products table seeded---' AS '';